# Generated by Django 5.2.1 on 2025-06-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'SUPERUSER'), ('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', max_length=10),
        ),
    ]
