# Generated by Django 5.2.2 on 2025-08-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Ruta', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('km', models.IntegerField(default=0)),
                ('tiempo', models.IntegerField(default=0)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='viaje.viaje')),
            ],
        ),
    ]
