# Generated by Django 5.2.1 on 2025-08-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='nombre_Ruta',
            field=models.CharField(default='Sin definir', max_length=50),
            preserve_default=False,
        ),
    ]
