# Generated by Django 5.2.2 on 2025-08-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_ruta_nombre_ruta'),
        ('viaje', '0002_remove_viaje_medio_remove_viaje_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='viaje',
            field=models.ForeignKey(default='Sin definir', on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='viaje.viaje'),
            preserve_default=False,
        ),
    ]
