# Generated by Django 5.2.1 on 2025-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_remove_ruta_viaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='km',
            new_name='distancia',
        ),
    ]
