# Generated by Django 5.2.1 on 2025-12-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0003_rename_km_ruta_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre_Ruta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=255),
        ),
    ]
