# Generated by Django 5.2.1 on 2025-08-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='destino_Viaje',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='origen_Viaje',
            new_name='origen',
        ),
    ]
