# Generated by Django 5.2.2 on 2025-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='medio',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='ruta',
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_Viaje',
            field=models.CharField(default='Sin definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_Viaje',
            field=models.CharField(default='Sin definir', max_length=100),
            preserve_default=False,
        ),
    ]
