# Generated by Django 5.2.2 on 2025-08-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0002_remove_medio_viaje'),
        ('ruta', '0002_remove_ruta_viaje'),
        ('viaje', '0002_rename_destino_viaje_viaje_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='medio.medio'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='ruta.ruta'),
        ),
    ]
