# Generated by Django 5.2.1 on 2025-12-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0003_viaje_medio_viaje_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
