# Generated by Django 5.2.1 on 2025-12-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0004_viaje_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
