# Generated by Django 5.2.1 on 2025-12-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0005_alter_viaje_destino_alter_viaje_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
