# Generated by Django 5.2.1 on 2026-03-07 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0004_alter_medio_nombre_medio'),
        ('ruta', '0004_alter_ruta_destino_alter_ruta_nombre_ruta_and_more'),
        ('viaje', '0006_alter_viaje_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='viaje',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='viaje',
            name='rango_fechas',
            field=models.CharField(default='Sin especificar', max_length=150),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medio.medio'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.ruta'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
