# Generated by Django 5.2.1 on 2026-03-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
        ('viaje', '0007_remove_viaje_fecha_fin_remove_viaje_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='alojamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alojamiento.alojamiento'),
        ),
    ]
