# Generated by Django 5.2.1 on 2026-03-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0008_viaje_alojamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='itinerario',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='motivo_viaje',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones y Ocio'), ('TRABAJO', 'Negocios y Trabajo'), ('AVENTURA', 'Turismo Aventura'), ('RELAX', 'Descanso y Relax'), ('LUNA_DE_MIEL', 'Luna de Miel / Romántico'), ('CULTURAL', 'Cultural e Histórico'), ('OTRO', 'Otro')], default='VACACIONES', max_length=50),
        ),
    ]
