# Generated by Django 5.2.1 on 2026-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0009_viaje_itinerario_viaje_motivo_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='cantidad_adultos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='viaje',
            name='cantidad_ninos',
            field=models.IntegerField(default=0),
        ),
    ]
