# Generated by Django 5.2.2 on 2025-08-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Medio', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('MARITIMO', 'Marítimo'), ('AEREA', 'Aérea'), ('SIN DEFINIR', 'Sin definir'), ('PÚBLICO COMBINADO', 'Público combinado'), ('PRIVADO COMBINADO', 'Privado combinado'), ('SIN DEFINIR', 'Sin definir')], default='SIN DEFINIR', max_length=20)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='viaje.viaje')),
            ],
        ),
    ]
