# Generated by Django 5.2.2 on 2025-08-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medio',
            name='viaje',
        ),
    ]
