# Generated by Django 5.2.1 on 2025-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('MARITIMO', 'Maritimo'), ('AEREA', 'Aerea'), ('SIN DEFINIR', 'Sin definir'), ('PÚBLICO COMBINADO', 'Público combinado'), ('PRIVADO COMBINADO', 'Privado combinado')], default='Sin definir', max_length=20),
        ),
    ]
