# Generated by Django 5.2.1 on 2025-08-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0002_alter_medio_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medio',
            old_name='nombre',
            new_name='nombre_Medio',
        ),
    ]
