# Generated by Django 5.2.2 on 2025-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0002_remove_medio_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
