# Generated by Django 5.2.2 on 2025-08-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0003_rename_nombre_medio_nombre_medio'),
        ('viaje', '0002_remove_viaje_medio_remove_viaje_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='viaje',
            field=models.ForeignKey(default='Sin definir', on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='viaje.viaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('MARITIMO', 'Marítimo'), ('AEREA', 'Aérea'), ('SIN DEFINIR', 'Sin definir'), ('PÚBLICO COMBINADO', 'Público combinado'), ('PRIVADO COMBINADO', 'Privado combinado')], default='Sin definir', max_length=20),
        ),
    ]
