# Generated by Django 5.2.1 on 2025-12-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0003_medio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='nombre_Medio',
            field=models.CharField(max_length=255),
        ),
    ]
