# Generated by Django 5.2.1 on 2026-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medio', '0004_alter_medio_nombre_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medio',
            name='plataforma_recomendada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
