# Generated by Django 5.2.1 on 2026-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sugerido', models.CharField(max_length=255)),
                ('plataforma_recomendada', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
