# Generated by Django 5.2.1 on 2025-09-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, default='profile_pictures/default.png', max_length=500, null=True),
        ),
    ]
