# Generated by Django 5.2.1 on 2025-09-23 15:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_opw0zi', max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
