# Generated by Django 5.2.1 on 2025-12-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_google_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('ARS', 'Pesos Arg (ARS)'), ('EUR', 'Euros (EUR)')], default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='distance_unit',
            field=models.CharField(choices=[('KM', 'Kilómetros'), ('MI', 'Millas')], default='KM', max_length=2),
        ),
    ]
